file_format: "1"
id: ownkb
name: ownkb
type: shield
url: https://github.com/dnlbauer/splitkeyboard
requires: [pro_micro]
features:
  - keys
#  - display  TODO remove?
#  - encoder  TODO use
siblings:
  - ownkb_left
  - ownkb_right
